name: Bug Report
description: Report a general package issue. Filling in the issue template is mandatory, issues without it will be closed.
title: "[Bug]: "
labels: [ bug ]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Is the bug applicable and reproducible to the latest version of the action and hasn't it been reported before?
      options:
        - label: Yes, it's still reproducible
          required: true
  - type: input
    attributes:
      label: What version of lighthouse-box are you using?
      description: 'For example: 1.0.3'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe your issue
      description: Describe the problem you're seeing, Please be short, but concise.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How can the issue be reproduced?
      description: Please provide easy-to-reproduce steps (repository, simple code example, failing unit test).
    validations:
      required: true
  - type: textarea
    attributes:
      label: What should be the expected behaviour?
      description: Please describe what the expected outcome should be. Any suggestions to what is wrong?
    validations:
      required: true
