import * as core from '@actions/core';
import { METRIC_LABELS, type LighthouseMetrics } from './types.js';
import { ACTION_URL, ACTION_VERSION, isRunningInGitHubActions } from './config.js';

type SummaryTableCell = { data: string; header?: boolean } | string;
type SummaryTableRow = SummaryTableCell[];

function buildSummaryTable(metrics: LighthouseMetrics): SummaryTableRow[] {
  const table: SummaryTableRow[] = [
    [{ data: 'Category', header: true }, { data: 'Result', header: true }],
  ];

  for (const [key, score] of Object.entries(metrics)) {
    const label = METRIC_LABELS[key as keyof LighthouseMetrics];
    table.push([label, `${score}%`]);
  }

  return table;
}

export async function printSummary(
  metrics: LighthouseMetrics,
  url: string,
  shouldWrite: boolean
): Promise<void> {
  if (!isRunningInGitHubActions()) {
    printToConsole(metrics, url);
    return;
  }

  const table = buildSummaryTable(metrics);

  const summary = core.summary
    .addHeading('Results')
    .addTable(table)
    .addBreak()
    .addRaw('Lighthouse metrics for ')
    .addLink(url, url)
    .addRaw(' generated by ')
    .addLink(`lighthouse-box/${ACTION_VERSION}`, ACTION_URL);

  if (shouldWrite) {
    await summary.write();
  } else {
    console.log(summary.stringify());
  }
}

function printToConsole(metrics: LighthouseMetrics, url: string): void {
  console.log('\n=== Lighthouse Results ===');
  console.log(`URL: ${url}\n`);

  for (const [category, score] of Object.entries(metrics)) {
    console.log(`${category}: ${score}%`);
  }

  console.log('\n===========================\n');
}
